# Project information
site_name: 'FMCS HELP TEST'
site_description: 'FMCS HELP is a place for all FAQs related to freemcserver.net'
site_url: 'https://test.fmcshelp.tk/'

# Copyright
copyright: '&copy; 2020 FMCS HELP TEST'

# Configuration
docs_dir: 'docs'
theme:
  name: 'material'
  custom_dir: 'theme'
  language: 'en'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  palette:
    primary: 'light-green'
    accent: 'light-green'
  feature:
    tabs: true
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  favicon: 'https://freemcserver.net/img/logo.png'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search

# Customization
extra:
  manifest: 'manifest.json'
  search:
    language: 'en'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/freemcservernet'

# Page tree
nav:
  - Home: index.md
  - Terms of Service: tos.md
  - Youtube Channel: youtube-channel.md
  - Getting Started: 
    - Introduction: getting-started/index.md
    - Control Panel: getting-started/control-panel.md
  - Java: 
    - Introduction: java/index.md
    - Custom IP: java/custom-ip.md
    - Custom Jar: java/custom-jar.md
    - Java Plugins: java/java-plugins.md
  - Bedrock:
    - Introduction: nukkit/index.md
    - Nukkit Plugins: nukkit/nukkit-plugins.md
  - Site Builder: 
    - Introduction: site-builder/index.md
    - Basics: site-builder/basics.md
    - Advanced: site-builder/advanced.md
  - Discord Server:
    - Server Rules: discord-server/server-rules.md
    - Server Advertising Rules: discord-server/advertising-rules.md
    - Nitro Boosting Info: discord-server/nitro-boost-info.md